version: "3.7"

services:
  consumer:
    image: flask-app
    tty: true
    ports:
      - "8000:80"
    environment:
      - PRODUCER_PORT=9000
  
  producer: 
    image: flask-app
    tty: true
    ports:
      - "9000:80"
    environment:
      - PRODUCER_PORT=8000